lab7/step5-django/myfirst/myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns=[
    path('',views.index, name='index'),
    path('<int:article_id>/',views.detail, name='detail'),
    path('<int:article_id>/leave_comment/',views.leave_comment, name='leave_comment'),
    

]

lab7/step5-django/myfirst/myfirst/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

lab7/step5-django/myfirst/myfirst/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
	article_title=models.CharField("название статьи", max_length=200)
	article_text=models.TextField("текст статьи")
	public_date=models.DateTimeField("дата публикация")

	def __str__(self):
		return self.article_title



	def recently_publicated(self):
	    return self.public_date >= (timezone.now() - datetime.timedelta(days = 7))


class Comment(models.Model):
	article=models.ForeignKey(Article, on_delete=models.CASCADE)
	author_name=models.CharField("имя автора", max_length=50)
	comment_text=models.TextField("текст комментария",max_length=200)


	def __str__(self):
		return self.author_name

lab7/step5-django/myfirst/myfirst/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article, Comment


def index(request):
	latest_articles_list = Article.objects.order_by('-public_date')[:5]
	return render(request, 'articles/list.html',{'latest_articles_list':latest_articles_list})

def detail(request,article_id):
	try:
		a= Article.objects.get( id= article_id)
	except:
	    raise Http404("Articles didnt find")

	latest_comments_list=a.comment_set.order_by('-id')[:10]    

	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})    	


def leave_comment(request,article_id):
    try:
    	a= Article.objects.get( id = article_id)
    except:
    	raise Http404("Comments didnt find")
    
    
    a.comment_set.create(author_name = request.POST['name'], comment_text=request.POST['text'])
    
    return HttpResponseRedirect(reverse('articles:detail', args = (a.id,)))

lab7/step5-django/myfirst/myfirst/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}} {% endblock %}

{% block content %} 

<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.public_date}}</em>

{% if article.recently_publicated %}
NEW ARTICLE
{% endif %}

<hr>

{% if latest_comments_list %}
    {% for c in latest_comments_list %}
         <p>
         	<strong>{{c.author_name}}</strong>
         	<p>{{c.comment_text}}</p>
         </p>
    {% endfor %}


{% endif %}    


 <hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
	
	{% csrf_token %}

	<input type="text" required placeholder="Your name" name="name"><br>
	<textarea name="text" required="" placeholder="Textfor comments" cols="30" rows="10"></textarea><br>

	<button type="submit"> Leave comment </button>
</form>
  
{% endblock %}

lab7/step5-django/myfirst/myfirst/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} Last articles {% endblock %}

{% block content %} 
    
   {% if latest_articles_list %}

       {% for a in latest_articles_list%}
           <a href="{% url 'articles:detail' a.id  %}">{{a.article_title}} </a>
       {% endfor %}

   {% else %}
       Articles didnt find...

   {% endif %}

{% endblock %}

lab7/step5-django/myfirst/myfirst/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} My site {%endblock %}</title>
</head>
<body>

	{% block content %}{% endblock %}

</body>
</html>	